---
title: 'Astro Pi: Mission Zero'
hero_image: images/MZ_banner_2024_V4.png
description: Prepare for Mission Zero
listed: false
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
- title: Step 1
- title: Step 2
- title: Step 3
- title: Step 4
- title: Step 5
- title: Step 6

