---
title: 'Astro Pi: Mission Zero'
hero_image: images/MZ_banner_2024_V4.png
description: Prepare for Mission Zero
listed: false
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
landing: true
steps:
  - title: Astro Pi Mission Zero
  - title: Colour the LEDs
    completion:
      - engaged
  - title: Colour different LEDs
  - title: Draw a picture
  - title: Sense a colour
    completion:
      - internal
  - title: Keep the colour changing
    completion:
      - external
