---
title: 'Astro Pi: Mission Zero'
hero_image: images/MZ_banner_2024_V4.png
description: Prepare for Mission Zero
listed: false
copyedit: true
version: 5.0.0
last_tested: 2018-06-12
steps:
- title: Step 1
